### ISSUE TITLE
Benefit of using this over normal resources

### ISSUE THREAD

**Issue by ThePat02** [Anaxarchus/gdscript-structs#1]
Structs are something Godot is sadly lacking at the moment. What is the benefit of your method if you could just use something like

```gdscript
class_name MyStruct extends Resource

var struct_property_int: int
var struct_property_string: String
var struct_property_custom: CustomClass
```

Is your solution simply a wrapper with some handy methods?

**Comment by Anaxarchus** [comment]
The primary benefit of using this class is in memory usage. At 100,000 resources your memory usage is already going to be about 150mb when using resources, and that's before you've added anything to it. For Structs using this Server pattern, those same objects are around 5mb. You can trivially maintain millions of structs, where using Godot's Objects and Nodes will be using gigabytes of memory at that point.

**Comment by ThePat02** [comment]
Would you mind explaining where the saved memory comes from? I think I am not really grasping on how this optimization works, as structs are still Godot resources.

**Comment by Anaxarchus** [comment]
Sure, Godot Class Objects such as: Object, Resource, Node, etc; Carry a lot of extra overhead with them. There is a lot of metadata being kept in them and a lot of metadata being kept about them. This allows you to do very convenient things, such as `get_instance_by_id`, and other identity based operations.

These structs on the other hand, have no identity, they are just an abstraction over what is essentially a table utilizing Godot's PackedArray types. The struct really only exists as a concept, in reality its data is columnized with all the other same-property values from the other instances. This is why the Struct is so memory efficient.

At this point, I should probably abandon framing this abstraction as Struct's, but for me, that is what I was implementing: An extremely lightweight, typed interface.

EDIT: To clarify one thing, you don't create a new Struct for each struct item. Each Struct Resource handles all of its instances. You don't actually instance the Struct Class to store a single object within it, you use it like one of Godot's servers to store thousands or millions of objects within it.

**Comment by ThePat02** [comment]
> To clarify one thing, you don't create a new Struct for each struct item. Each Struct Resource handles all of its instances. You don't actually instance the Struct Class to store a single object within it, you use it like one of Godot's servers to store thousands or millions of objects within it.

Oh, this makes a lot of sense now. I think changing the name to something different would be great, as it really isn't a struct in the traditional way. The naming just created confusion for me personally. Great idea tho, I will keep this one starred since I may need it for one of my future projects. 



Edit: Something like `DataServer` would fit very well!
